version: '3.8'

services:
  db-filler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - TURSO_DATABASE_URL=${TURSO_DATABASE_URL}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
    volumes:
      - ./dataset.xlsx:/app/dataset.xlsx
