version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: impress_back_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      # Add environment variables here if needed (e.g. database credentials)
    restart: always
